In [10]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df= pd.read_csv("customer_shopping_data.csv")
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

In [12]:
# To check the count of records grouped by region/branch of the mall
df.groupby("shopping_mall").count()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date
shopping_mall,,,,,,,,,
Cevahir AVM,4991,4991,4991,4991,4991,4991,4991,4991,4991
Emaar Square Mall,4811,4811,4811,4811,4811,4811,4811,4811,4811
Forum Istanbul,4947,4947,4947,4947,4947,4947,4947,4947,4947
Istinye Park,9781,9781,9781,9781,9781,9781,9781,9781,9781
Kanyon,19823,19823,19823,19823,19823,19823,19823,19823,19823
Mall of Istanbul,19943,19943,19943,19943,19943,19943,19943,19943,19943
Metrocity,15011,15011,15011,15011,15011,15011,15011,15011,15011
Metropol AVM,10161,10161,10161,10161,10161,10161,10161,10161,10161
Viaport Outlet,4914,4914,4914,4914,4914,4914,4914,4914,4914
Zorlu Center,5075,5075,5075,5075,5075,5075,5075,5075,5075

In [13]:
# To check the count of records grouped by the product categories

df.groupby("category").count()

,invoice_no,customer_id,gender,age,quantity,price,payment_method,invoice_date,shopping_mall
category,,,,,,,,,
Books,4981,4981,4981,4981,4981,4981,4981,4981,4981
Clothing,34487,34487,34487,34487,34487,34487,34487,34487,34487
Cosmetics,15097,15097,15097,15097,15097,15097,15097,15097,15097
Food & Beverage,14776,14776,14776,14776,14776,14776,14776,14776,14776
Shoes,10034,10034,10034,10034,10034,10034,10034,10034,10034
Souvenir,4999,4999,4999,4999,4999,4999,4999,4999,4999
Technology,4996,4996,4996,4996,4996,4996,4996,4996,4996
Toys,10087,10087,10087,10087,10087,10087,10087,10087,10087

In [14]:
# total sales for each category of product
df.groupby("category").sum()

,invoice_no,customer_id,gender,age,quantity,price,payment_method,invoice_date,shopping_mall
category,,,,,,,,,
Books,I337046I139207I294687I174250I117291I304265I202...,C189076C191708C300786C204553C134449C653385C317...,FemaleFemaleMaleFemaleMaleFemaleFemaleFemaleFe...,216882,14982,226977.30,CashCredit CardDebit CardCashCredit CardDebit ...,24/10/202128/10/202216/01/202116/12/20229/12/2...,KanyonEmaar Square MallMetrocityMetrocityZorlu...
Clothing,I138884I127801I227836I293112I293455I326945I179...,C241288C266599C657758C176086C159642C283361C312...,FemaleMaleFemaleFemaleMaleFemaleMaleFemaleFema...,1497054,103558,31075684.64,Credit CardCashCredit CardCredit CardCredit Ca...,5/8/20229/11/202124/05/202213/01/20214/11/2021...,KanyonMetrocityForum IstanbulMall of IstanbulM...
Cosmetics,I121056I196704I209744I138674I752693I267193I269...,C151197C289625C251229C155059C306662C317818C126...,FemaleFemaleMaleMaleFemaleFemaleMaleFemaleFema...,657937,45465,1848606.90,CashCredit CardCredit CardCredit CardCashCredi...,13/03/202220/04/202229/04/202114/02/202228/04/...,Istinye ParkMall of IstanbulIstinye ParkMetrop...
Food & Beverage,I306368I195744I412481I339732I246550I137794I263...,C240286C330667C125696C276887C716788C133687C112...,FemaleFemaleFemaleMaleFemaleFemaleFemaleFemale...,640605,44277,231568.71,CashCredit CardCashCredit CardCashDebit CardCa...,25/12/20225/1/20221/5/20214/1/202310/9/202112/...,MetrocityZorlu CenterCevahir AVMEmaar Square M...
Shoes,I317333I173702I688768I217053I655874I768348I167...,C111565C988172C362288C192344C447138C176727C164...,MaleFemaleMaleMaleFemaleFemaleFemaleFemaleFema...,436027,30217,18135336.89,Debit CardCredit CardCredit CardCashCashCredit...,12/12/202116/05/20217/11/202110/10/202223/08/2...,Forum IstanbulMetropol AVMViaport OutletEmaar ...
Souvenir,I204979I870944I151332I317105I317140I141241I285...,C173084C169749C168491C177975C326893C143442C194...,FemaleMaleMaleFemaleFemaleMaleFemaleFemaleFema...,216922,14871,174436.83,Debit CardCredit CardCashDebit CardCashCredit ...,14/03/20218/6/202125/03/202129/07/202119/10/20...,Istinye ParkCevahir AVMKanyonKanyonIstinye Par...
Technology,I252275I160777I883721I289643I283443I164665I122...,C313348C626042C236859C584700C189493C255058C989...,MaleFemaleFemaleFemaleMaleFemaleFemaleFemaleFe...,216669,15021,15772050.00,CashCashCredit CardCashCredit CardCashCredit C...,26/10/202122/02/202219/11/202122/08/202225/05/...,KanyonMetrocityMall of IstanbulKanyonViaport O...
Toys,I640508I992454I195396I161949I258195I181109I260...,C225330C196845C285161C159164C213742C119549C258...,FemaleMaleMaleFemaleMaleMaleMaleMaleFemaleFema...,437032,30321,1086704.64,Debit CardCashDebit CardDebit CardCashCashCash...,31/07/20227/3/202316/05/20214/7/202226/11/2021...,MetrocityCevahir AVMIstinye ParkMall of Istanb...

In [15]:
#to get the top performing branches

df.sort_values(by = "price", ascending = False)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
26201,I321861,C140969,Male,30,Technology,5,5250.00,Debit Card,23/12/2021,Istinye Park
86791,I989037,C873836,Female,54,Technology,5,5250.00,Cash,16/03/2022,Metrocity
86793,I292024,C142240,Female,50,Technology,5,5250.00,Cash,14/03/2021,Istinye Park
41870,I258591,C174024,Female,27,Technology,5,5250.00,Cash,9/11/2022,Metropol AVM
7559,I148353,C138646,Female,38,Technology,5,5250.00,Cash,13/09/2022,Kanyon
...,...,...,...,...,...,...,...,...,...,...
68116,I890429,C171182,Female,54,Food & Beverage,1,5.23,Credit Card,20/04/2021,Metropol AVM
68131,I434373,C291211,Male,67,Food & Beverage,1,5.23,Cash,3/6/2021,Kanyon
10738,I173726,C141669,Female,26,Food & Beverage,1,5.23,Credit Card,7/7/2021,Mall of Istanbul
50272,I732484,C220354,Male,19,Food & Beverage,1,5.23,Debit Card,3/5/2021,Forum Istanbul
19011,I129041,C271857,Female,20,Food & Beverage,1,5.23,Debit Card,16/12/2022,Kanyon

In [16]:

# to get the top selling categories
df = df.sort_values(by='price', ascending=False)

In [17]:
# to get total sales for each combination of branch and product_category
df.groupby(["shopping_mall", "category"]).sum()

                                                                      invoice_no  \
shopping_mall category
Cevahir AVM   Books            I130458I322200I185831I130107I997276I302776I308...
              Clothing         I397213I320505I242807I273799I231955I288822I327...
              Cosmetics        I421180I273599I219278I133142I119070I100198I108...
              Food & Beverage  I227896I330464I161413I136825I329607I131798I314...
              Shoes            I114368I875342I299206I385587I200448I312085I229...
...                                                                          ...
Zorlu Center  Food & Beverage  I305229I275944I333804I156499I734722I261336I226...
              Shoes            I169625I319054I245166I133437I851843I112057I533...
              Souvenir         I316426I170625I310770I210435I173724I182997I183...
              Technology       I315595I864398I161521I229087I473614I203409I327...
              Toys             I934742I186369I201162I268355I639684I580363I857...

                                                                     customer_id  \
shopping_mall category
Cevahir AVM   Books            C289953C287279C518352C836842C284567C108844C486...
              Clothing         C410751C164515C228901C315869C250026C348970C591...
              Cosmetics        C270614C210081C208144C329997C310567C136883C229...
              Food & Beverage  C190658C324131C896023C287485C299741C274558C184...
              Shoes            C269720C129212C178279C284510C260637C203296C932...
...                                                                          ...
Zorlu Center  Food & Beverage  C211824C181295C152426C137784C889422C109444C114...
              Shoes            C197284C225222C194082C141622C207602C318582C220...
              Souvenir         C115862C150664C625764C517862C144853C225027C223...
              Technology       C133751C257500C663637C164910C228258C217552C338...
              Toys             C159097C168043C177517C316607C283635C139556C163...

                                                                          gender  \
shopping_mall category
Cevahir AVM   Books            MaleMaleFemaleMaleFemaleMaleFemaleMaleFemaleMa...
              Clothing         MaleMaleFemaleMaleMaleFemaleFemaleFemaleFemale...
              Cosmetics        FemaleFemaleFemaleMaleMaleFemaleFemaleMaleMale...
              Food & Beverage  FemaleMaleFemaleMaleFemaleFemaleFemaleFemaleMa...
              Shoes            FemaleFemaleFemaleMaleFemaleFemaleFemaleFemale...
...                                                                          ...
Zorlu Center  Food & Beverage  MaleFemaleFemaleFemaleFemaleMaleFemaleFemaleFe...
              Shoes            FemaleFemaleFemaleFemaleFemaleFemaleFemaleMale...
              Souvenir         MaleMaleFemaleFemaleFemaleMaleFemaleFemaleFema...
              Technology       MaleFemaleMaleFemaleFemaleFemaleFemaleFemaleFe...
              Toys             FemaleFemaleFemaleFemaleFemaleFemaleMaleMaleFe...

                                 age  quantity       price  \
shopping_mall category
Cevahir AVM   Books            11464       792    11998.80
              Clothing         74729      5180  1554414.40
              Cosmetics        31142      2174    88394.84
              Food & Beverage  33269      2293    11992.39
              Shoes            21211      1473   884050.41
...                              ...       ...         ...
Zorlu Center  Food & Beverage  32687      2216    11589.68
              Shoes            22949      1589   953670.13
              Souvenir         10727       716     8398.68
              Technology       10533       765   803250.00
              Toys             22395      1526    54691.84

                                                                  payment_method  \
shopping_mall category
Cevahir AVM   Books            Debit CardCashDebit CardCredit CardCredit Card...
              Clothing         Debit CardCashCredit CardDebit CardCashCashCas...
              Cosmetics        CashCashCredit CardCredit CardCredit CardCredi...
              Food & Beverage  CashDebit CardCredit CardCashCashCashCashCashC...
              Shoes            Credit CardCredit CardCashCashCredit CardCredi...
...                                                                          ...
Zorlu Center  Food & Beverage  Credit CardDebit CardCredit CardCredit CardCre...
              Shoes            Debit CardCredit CardCashDebit CardCredit Card...
              Souvenir         Debit CardCashDebit CardCashCredit CardDebit C...
              Technology       Credit CardCredit CardDebit CardCredit CardDeb...
              Toys             CashCashDebit CardDebit CardCashCashCashDebit ...

                                                                    invoice_date
shopping_mall category
Cevahir AVM   Books            11/4/202127/03/20216/3/202316/06/20226/12/2021...
              Clothing         27/08/202222/11/202123/02/202213/08/202212/2/2...
              Cosmetics        22/06/20222/2/202113/06/202119/07/202111/9/202...
              Food & Beverage  4/4/202218/02/202110/3/202219/06/202123/06/202...
              Shoes            13/06/202126/05/202218/05/202212/11/202216/03/...
...                                                                          ...
Zorlu Center  Food & Beverage  22/03/20221/11/202126/07/202117/02/202314/02/2...
              Shoes            30/07/20217/1/202214/04/20214/6/20228/2/202113...
              Souvenir         15/03/202119/02/20215/8/202222/07/20227/1/2023...
              Technology       22/08/202119/01/20227/1/202112/3/202214/02/202...
              Toys             25/03/202225/08/20224/6/202130/05/202228/08/20...

[80 rows x 8 columns]

In [ ]:
# pie chart for sales by branch

plt.pie(df["price"], labels = df.index)
plt.show()

In [ ]:
# pie chart for sales by product category

plt.pie(category_sales["price"], labels = category_sales.index)
plt.show()

In [ ]:
combined_pivot = df.pivot_table(index="shopping_mall", columns="category", values="price", aggfunc="sum")

In [ ]:
# grouped bar chart for sales of different categories at different branches

combined_pivot.plot(kind="bar", figsize=(10, 6))
plt.show()